image: electronuserland/builder:wine

cache:
  paths:
    - storywriter-main/node_modules/

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  only: master
  script:
    - cd storywriter-main
    - yarn jest:unit

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  only: master
  script:
    - cd storywriter-main
    - yarn electron:build

